### ISSUE TITLE
Implement `debounce` operator

### ISSUE THREAD

**Issue by mihaisoloi** [monifu/monifu#53] opened 2015-08-04 08:16 UTC
The `debounce` operator is an important one as it lets the Observable emit an element after a certain timespan has elapsed. Here is the description: http://reactivex.io/documentation/operators/debounce.html

**Comment by alexandru** [comment] 2015-08-06 13:28
Closing as duplicate of #41.

**Closed by alexandru** 2015-08-06 13:28 UTC
